version: "2"

services:
  db:
    image: postgres
    container_name: "${COMPOSE_PROJECT_NAME}_postgre"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
       - '../.data/postgres:/var/lib/postgresql/data:cached'
    ports:
      - "5432:5432"
    networks:
      - front

  # mailhog:
  #   image: skilldlabs/mailhog
  #   container_name: "${COMPOSE_PROJECT_NAME}_mail"
  #   restart: always
  #   networks:
  #     - front
  #   ports:
  #     - 8025:8025

networks:
  front:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "${IPRANGE}"
